Repository precice/fenics-adapter, pull requests merged in 2020-11, with the labels that each got.

#95 Add CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#104 Implement O(N) algorithm for coupling edge detection
  fenicsprecice/adapter_core.py
  tests/test_adapter_core.py
Labels: enhancement

#101 Overhaul Initialization
  fenicsprecice/adapter_core.py
  fenicsprecice/fenicsprecice.py
  tests/test_fenicsprecice.py
Labels: enhancement

#106 Use versioneer for __version__
  .gitattributes
  MANIFEST.in
  fenicsprecice/__init__.py
  fenicsprecice/_version.py
  fenicsprecice/version.py
  setup.cfg
  setup.py
  tests/test_fenicsprecice.py
  versioneer.py
Labels: bug
