Repository precice/fenics-adapter, pull requests merged in 2020-08, with the labels that each got.

#79 Provide adapter version to user
  fenicsadapter/__init__.py
  fenicsadapter/version.py
  setup.py
Labels: compatibility

#81 Fix data initialization
  fenicsadapter/expression_core.py
  fenicsadapter/fenicsadapter.py
  tests/test_fenicsadapter.py
Labels: bug

#83 Replace ExactInterpolationExpression with SegregatedRBFinterpolationExpression
  fenicsadapter/expression_core.py
  fenicsadapter/fenicsadapter.py
  tests/precice-adapter-config.json
Labels: enhancement

#82 Change format of read data
  fenicsadapter/expression_core.py
  fenicsadapter/fenicsadapter.py
  tests/test_fenicsadapter.py
  tests/test_write_read.py
Labels: enhancement
