Repository precice/fenics-adapter, pull requests merged in 2025-03, with the labels that each got.

#195 Restrict SciPy version
  CHANGELOG.md
  setup.py
Labels: compatibility

#197 Introduce tox for testing
  .github/workflows/build-and-test.yml
  README.md
  tox.ini
Labels: maintainability

#198 Install fenics-adapter in venv for running tutorials
  .github/workflows/run-tutorials.yml
Labels: bug, maintainability

#199 Fix workflow_dispatch for tag
  .github/workflows/run-tutorials.yml
Labels: maintainability
